/** Every distinct atlas part name with system 'arterial' (426 names, 639 parts). Generated, not hand-written: rerun
 * node -e "const a=require('./public/anyhealth/models/atlas.json');console.log(JSON.stringify([...new Set(a.parts.filter(p=>p.system==='arterial').map(p=>p.name))].sort()))"
 * and paste the result if the atlas changes. Hardcoded so client code does not import atlas.json. */
export const ARTERIAL_PARTS:readonly string[]=[
	'Abdominal aorta',
	'Accessory subsuperior branch of right posterior basal segmental artery',
	'Acromial branch of left thoraco-acromial artery',
	'Acromial branch of right thoraco-acromial artery',
	'Anterior branch of lateral segmental artery',
	'Anterior branch of right anterior segmental artery',
	'Anterior cecal artery',
	'Anterior communicating artery',
	'Anterior division of left renal artery',
	'Anterior division of right renal artery',
	'Anterior inferior cerebellar artery',
	'Anterior inferior pancreaticoduodenal artery',
	'Anterior inferior segmental hepatic artery',
	'Anterior part of right apical segmental artery',
	'Anterior superior pancreaticoduodenal artery',
	'Anterior superior segmental hepatic artery',
	'Anterior temporal branch of left lateral occipital artery',
	'Anterior temporal branch of right lateral occipital artery',
	'Anterolateral central branch of left middle cerebral artery',
	'Anterolateral central branch of right middle cerebral artery',
	'Apical part of right apical segmental artery',
	'Apical part of right posterior segmental artery',
	'Appendicular artery',
	'Arch of aorta',
	'Artery of central sulcus',
	'Artery of left postcentral sulcus',
	'Artery of left precentral sulcus',
	'Artery of right postcentral sulcus',
	'Artery of right precentral sulcus',
	'Ascending aorta',
	'Ascending branch of inferior branch of ileocolic artery',
	'Ascending branch of left colic artery',
	'Basal branch of right anterior basal segmental artery',
	'Basilar artery',
	'Brachiocephalic artery',
	'Branch of left anterior choroidal artery to posterior limb of left internal capsule',
	'Branch of left middle cerebral artery to left angular gyrus',
	'Branch of right anterior choroidal artery to posterior limb of right internal capsule',
	'Branch of right middle cerebral artery to right angular gyrus',
	'Bronchial artery',
	'Bronchial branch of arch of aorta',
	'Caudal pancreatic artery',
	'Caudate lobe branch of left hepatic artery',
	'Caudate lobe branch of right hepatic artery',
	'Celiac artery',
	'Celiac trunk',
	'Circumflex branch of left coronary artery',
	'Common hepatic artery',
	'Conus branch of anterior interventricular branch of left coronary artery',
	'Deltoid branch of left thoraco-acromial artery',
	'Deltoid branch of right thoraco-acromial artery',
	'Descending aorta',
	'Descending branch of left colic artery',
	'Descending branch of left lateral circumflex femoral artery',
	'Descending branch of right lateral circumflex femoral artery',
	'Descending thoracic aorta',
	'Diagonal branch of anterior descending branch of left coronary artery',
	'Distal perforating artery',
	'Dorsal carpal branch of left radial artery',
	'Dorsal carpal branch of right radial artery',
	'Dorsal digital artery of foot',
	'Dorsal pancreatic artery',
	'Esophageal artery',
	'First anterior ventricular branch of right coronary artery',
	'First posterior ventricular branch of right coronary artery',
	'First right anterior branch of anterior interventricular branch of left coronary artery',
	'First septal branch of right posterior interventricular artery',
	'Great pancreatic artery',
	'Hepatic artery proper',
	'Hypothalamic branch of left posterior communicating artery',
	'Hypothalamic branch of right posterior communicating artery',
	'Ileal artery',
	'Ileal branch of inferior branch of ileocolic artery',
	'Ileocolic artery',
	'Inferior branch of medial segmental artery',
	'Inferior lingular artery',
	'Inferior mesenteric artery',
	'Inferior pancreatic artery',
	'Inferior pancreaticoduodenal artery',
	'Inferior segmental branch of left renal artery',
	'Inferior segmental branch of right renal artery',
	'Insular part of left middle cerebral artery',
	'Insular part of right middle cerebral artery',
	'Intermediomedial branch of left callosomarginal artery',
	'Intermediomedial branch of right callosomarginal artery',
	'Lateral branch of left pontine artery',
	'Lateral branch of left superior cerebellar artery',
	'Lateral branch of right anterior basal segmental artery',
	'Lateral branch of right lateral basal segmental artery',
	'Lateral branch of right pontine artery',
	'Lateral branch of right superior cerebellar artery',
	'Lateral branch of right superior segmental artery',
	'Lateral inferior segmental hepatic artery',
	'Lateral proper palmar digital artery of left little finger',
	'Lateral proper palmar digital artery of left middle finger',
	'Lateral proper palmar digital artery of left ring finger',
	'Lateral proper palmar digital artery of right little finger',
	'Lateral proper palmar digital artery of right middle finger',
	'Lateral proper palmar digital artery of right ring finger',
	'Lateral superior segmental hepatic artery',
	'Laterobasal branch of right posterior basal segmental artery',
	'Left anterior basal segmental artery',
	'Left anterior cerebral artery',
	'Left anterior choroidal artery',
	'Left anterior circumflex humeral artery',
	'Left anterior interosseous artery',
	'Left anterior parietal artery',
	'Left anterior segmental artery',
	'Left anterior spinal artery',
	'Left anterior temporal artery',
	'Left anterior tibial artery',
	'Left anterior tibial recurrent artery',
	'Left anterior ulnar recurrent artery',
	'Left apical segmental artery',
	'Left arcuate artery',
	'Left arteria princeps pollicis',
	'Left arteria radialis indicis',
	'Left axillary artery',
	'Left brachial artery',
	'Left callosomarginal artery',
	'Left circumflex scapular artery',
	'Left colic artery',
	'Left common carotid artery',
	'Left common iliac artery',
	'Left common interosseous artery',
	'Left costocervical trunk',
	'Left deep brachial artery',
	'Left deep cervical artery',
	'Left deep palmar arch',
	'Left deep plantar artery',
	'Left descending genicular artery',
	'Left dorsal artery of penis',
	'Left dorsal carpal branch of ulnar artery',
	'Left dorsal scapular artery',
	'Left dorsalis pedis artery',
	'Left external iliac artery',
	'Left femoral artery',
	'Left first common palmar digital artery',
	'Left first posterior intercostal artery',
	'Left fourth common palmar digital artery',
	'Left gastric artery',
	'Left gastro-epiploic artery',
	'Left inferior epigastric artery',
	'Left inferior lateral genicular artery',
	'Left inferior medial genicular artery',
	'Left inferior phrenic artery',
	'Left inferior suprarenal artery',
	'Left inferior thyroid artery',
	'Left inferior ulnar collateral artery',
	'Left internal carotid artery',
	'Left internal iliac artery',
	'Left internal thoracic artery',
	'Left lateral basal segmental artery',
	'Left lateral circumflex femoral artery',
	'Left lateral frontobasal artery',
	'Left lateral occipital artery',
	'Left lateral plantar artery',
	'Left lateral superior genicular artery',
	'Left lateral tarsal artery',
	'Left lateral thoracic artery',
	'Left lobe branch of left hepatic artery',
	'Left medial basal segmental artery',
	'Left medial frontobasal artery',
	'Left medial occipital artery',
	'Left medial plantar artery',
	'Left medial superior genicular artery',
	'Left middle genicular artery',
	'Left middle suprarenal artery',
	'Left musculophrenic artery',
	'Left ophthalmic artery',
	'Left palmar metacarpal artery',
	'Left pericallosal artery',
	'Left plantar arch',
	'Left polar temporal artery',
	'Left popliteal artery',
	'Left posterior basal segmental artery',
	'Left posterior circumflex humeral artery',
	'Left posterior communicating artery',
	'Left posterior inferior cerebellar artery',
	'Left posterior medial choroidal artery',
	'Left posterior parietal artery',
	'Left posterior segmental artery',
	'Left posterior tibial artery',
	'Left posterior ulnar recurrent artery',
	'Left prefrontal artery',
	'Left pulmonary artery',
	'Left radial artery',
	'Left radial recurrent artery',
	'Left recurrent interosseous artery',
	'Left renal artery',
	'Left second common palmar digital artery',
	'Left second posterior intercostal artery',
	'Left splenial artery',
	'Left subclavian artery',
	'Left subcostal artery',
	'Left subscapular artery',
	'Left superficial cervical artery',
	'Left superficial epigastric artery',
	'Left superficial medial plantar artery',
	'Left superficial palmar arterial arch',
	'Left superior cerebellar artery',
	'Left superior epigastric artery',
	'Left superior intercostal artery',
	'Left superior segmental artery',
	'Left superior ulnar collateral artery',
	'Left suprascapular artery',
	'Left testicular artery',
	'Left thalamogeniculate artery',
	'Left thalamoperforating artery',
	'Left third common palmar digital artery',
	'Left thoracodorsal artery',
	'Left thyrocervical trunk',
	'Left transverse cervical artery',
	'Left ulnar artery',
	'Left vertebral artery',
	'Lumbar artery',
	'Marginal artery of colon',
	'Marginal branch of right coronary artery',
	'Marginal colic artery',
	'Medial branch of left pontine artery',
	'Medial branch of left superior cerebellar artery',
	'Medial branch of right pontine artery',
	'Medial branch of right superior cerebellar artery',
	'Medial branch of right superior segmental artery',
	'Medial inferior segmental hepatic artery',
	'Medial proper palmar digital artery of left index finger',
	'Medial proper palmar digital artery of right index finger',
	'Medial proper palmar digital artery of right middle finger',
	'Medial proper palmar digital artery of right ring finger',
	'Medial superior segmental hepatic artery',
	'Mediobasal branch of right posterior basal segmental artery',
	'Middle colic artery',
	'Middle collateral branch of left deep brachial artery',
	'Middle collateral branch of right deep brachial artery',
	'Middle temporal branch of left lateral occipital artery',
	'Middle temporal branch of left middle cerebral artery',
	'Middle temporal branch of right lateral occipital artery',
	'Middle temporal branch of right middle cerebral artery',
	'Paracentral branch of left callosomarginal artery',
	'Paracentral branch of right callosomarginal artery',
	'Pectoral branch of left thoraco-acromial artery',
	'Pectoral branch of right thoraco-acromial artery',
	'Plantar metatarsal artery',
	'Postcommunicating part of left posterior cerebral artery',
	'Postcommunicating part of right posterior cerebral artery',
	'Posterior branch of lateral segmental artery',
	'Posterior branch of right anterior segmental artery',
	'Posterior cecal artery',
	'Posterior division of left renal artery',
	'Posterior division of right renal artery',
	'Posterior inferior pancreaticoduodenal artery',
	'Posterior inferior segmental hepatic artery',
	'Posterior intercostal arteries',
	'Posterior interventricular branch of right coronary artery',
	'Posterior part of right posterior segmental artery',
	'Posterior segmental branch of left renal artery',
	'Posterior segmental branch of right renal artery',
	'Posterior superior pancreaticoduodenal artery',
	'Posterior superior segmental hepatic artery',
	'Posterior temporal branch of left middle cerebral artery',
	'Posterior temporal branch of right middle cerebral artery',
	'Posteromedial branch of left callosomarginal artery',
	'Posteromedial branch of right callosomarginal artery',
	'Posteromedial central branch of left posterior cerebral artery',
	'Posteromedial central branch of right posterior cerebral artery',
	'Precommunicating part of left posterior cerebral artery',
	'Precommunicating part of right posterior cerebral artery',
	'Precuneal branch of left pericallosal artery',
	'Precuneal branch of right pericallosal artery',
	'Pulmonary trunk',
	'Radial collateral branch of left deep brachial artery',
	'Radial collateral branch of right deep brachial artery',
	'Right anterior cerebral artery',
	'Right anterior choroidal artery',
	'Right anterior circumflex humeral artery',
	'Right anterior interosseous artery',
	'Right anterior parietal artery',
	'Right anterior segmental artery',
	'Right anterior spinal artery',
	'Right anterior temporal artery',
	'Right anterior tibial artery',
	'Right anterior tibial recurrent artery',
	'Right anterior ulnar recurrent artery',
	'Right arcuate artery',
	'Right arteria princeps pollicis',
	'Right arteria radialis indicis',
	'Right axillary artery',
	'Right brachial artery',
	'Right callosomarginal artery',
	'Right circumflex scapular artery',
	'Right colic artery',
	'Right common carotid artery',
	'Right common iliac artery',
	'Right common interosseous artery',
	'Right conus artery',
	'Right costocervical trunk',
	'Right deep brachial artery',
	'Right deep cervical artery',
	'Right deep palmar arch',
	'Right deep plantar artery',
	'Right descending genicular artery',
	'Right dorsal artery of penis',
	'Right dorsal carpal branch of ulnar artery',
	'Right dorsal scapular artery',
	'Right dorsalis pedis artery',
	'Right external iliac artery',
	'Right femoral artery',
	'Right first common palmar digital artery',
	'Right first posterior intercostal artery',
	'Right fourth common palmar digital artery',
	'Right gastric artery',
	'Right gastro-epiploic artery',
	'Right inferior epigastric artery',
	'Right inferior lateral genicular artery',
	'Right inferior medial genicular artery',
	'Right inferior phrenic artery',
	'Right inferior suprarenal artery',
	'Right inferior thyroid artery',
	'Right inferior ulnar collateral artery',
	'Right internal carotid artery',
	'Right internal iliac artery',
	'Right internal thoracic artery',
	'Right lateral circumflex femoral artery',
	'Right lateral frontobasal artery',
	'Right lateral occipital artery',
	'Right lateral plantar artery',
	'Right lateral superior genicular artery',
	'Right lateral tarsal artery',
	'Right lateral thoracic artery',
	'Right lobe branch of right hepatic artery',
	'Right medial frontobasal artery',
	'Right medial occipital artery',
	'Right medial plantar artery',
	'Right medial superior genicular artery',
	'Right middle genicular artery',
	'Right middle suprarenal artery',
	'Right musculophrenic artery',
	'Right ophthalmic artery',
	'Right palmar metacarpal artery',
	'Right pericallosal artery',
	'Right plantar arch',
	'Right polar temporal artery',
	'Right popliteal artery',
	'Right posterior circumflex humeral artery',
	'Right posterior communicating artery',
	'Right posterior inferior cerebellar artery',
	'Right posterior medial choroidal artery',
	'Right posterior parietal artery',
	'Right posterior tibial artery',
	'Right posterior ulnar recurrent artery',
	'Right prefrontal artery',
	'Right pulmonary artery',
	'Right radial artery',
	'Right radial recurrent artery',
	'Right recurrent interosseous artery',
	'Right renal artery',
	'Right second common palmar digital artery',
	'Right second posterior intercostal artery',
	'Right splenial artery',
	'Right subclavian artery',
	'Right subcostal artery',
	'Right subscapular artery',
	'Right superficial cervical artery',
	'Right superficial epigastric artery',
	'Right superficial medial plantar artery',
	'Right superficial palmar arterial arch',
	'Right superior cerebellar artery',
	'Right superior epigastric artery',
	'Right superior intercostal artery',
	'Right superior ulnar collateral artery',
	'Right suprascapular artery',
	'Right testicular artery',
	'Right thalamogeniculate artery',
	'Right thalamoperforating artery',
	'Right third common palmar digital artery',
	'Right thoracodorsal artery',
	'Right thyrocervical trunk',
	'Right transverse cervical artery',
	'Right ulnar artery',
	'Right upper lobar artery',
	'Right vertebral artery',
	'Second right anterior branch of anterior interventricular branch of left coronary artery',
	'Second septal branch of right posterior interventricular artery',
	'Septal branch of anterior interventricular artery',
	'Set of calcaneal branches of posterior tibial artery',
	'Set of common plantar digital arteries',
	'Set of dorsal digital arteries',
	'Set of dorsal metacarpal arteries',
	'Set of oesophageal branches of thoracic aorta',
	'Set of perforating arteries',
	'Set of plantar digital arteries proper',
	'Set of posterior temporal branches of lateral occipital artery',
	'Sigmoid artery',
	'Sphenoid part of left middle cerebral artery',
	'Sphenoid part of right middle cerebral artery',
	'Splenic artery',
	'Superior branch of medial segmental artery',
	'Superior branch of right superior segmental artery',
	'Superior lingular artery',
	'Superior mesenteric artery',
	'Superior rectal artery',
	'Superior segmental branch of left renal artery',
	'Superior segmental branch of right renal artery',
	'Superior vermian branch of medial branch of left superior cerebellar artery',
	'Superior vermian branch of medial branch of right superior cerebellar artery',
	'Temporo-occipital branch of left middle cerebral artery',
	'Temporo-occipital branch of right middle cerebral artery',
	'Third right anterior branch of anterior interventricular branch of left coronary artery',
	'Trunk of anterior interventricular branch of left coronary artery',
	'Trunk of gastroduodenal artery',
	'Trunk of inferior terminal branch of left middle cerebral artery',
	'Trunk of inferior terminal branch of right middle cerebral artery',
	'Trunk of left coronary artery',
	'Trunk of left hepatic artery',
	'Trunk of left renal artery',
	'Trunk of left thoraco-acromial artery',
	'Trunk of right coronary artery',
	'Trunk of right hepatic artery',
	'Trunk of right renal artery',
	'Trunk of right thoraco-acromial artery',
	'Trunk of superior mesenteric artery',
	'Ureteric segment of left renal artery',
	'Ureteric segment of right renal artery',
	'anterior inferior cerebellar artery',
	'artery of central sulcus',
	'set of posterior temporal branches of lateral occipital artery',
];
